server:
  port: 80


spring:
  datasource:
    url: ${secrets.DATASOURCE_URL}
    username: ${secrets.DATASOURCE_USERNAME}
    password: ${secrets.DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: mysql
