server:
  port: 8080

spring:
  application:
    name: mulkkam
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver

  sql:
    init:
      data-locations: classpath:/data.sql
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

open-weather:
  api:
    key: temp-key
