spring:
  profiles:
    active: local
    include: private
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include:
          - health
