server:
  port: 8080

spring:
  application:
    name: mulkkam

  profiles:
    include: private
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  metrics:
    export:
      cloudwatch:
        namespace: Mulkkam/Dev
        step: 1m
        batchSize: 20
