server:
  port: 80

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true

logging:
  file:
    name: ${LOG_PATH}

fcm:
  secret-path: ${FCM_BASE64_ENCODING_KEY}
  project-id: ${FCM_PROJECT_ID}
