server:
  port: 8080

spring:
  application:
    name: mulkkam
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
