spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include:
          - health

security:
  jwt:
    secret-key: 910cf806fc2736a9365429796dc9f78e
    expire-length: 36000000
