server:
  port: 8080

spring:
  application:
    name: mulkkam

  profiles:
    include: private
    active: local

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
