name: Android CI

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./android

    steps:
    - uses: actions/checkout@v4
    
    - name: set up Base Url
      env:
        BASE_URL: ${{secrets.BASE_URL}}
      run:
        echo base.url=\"$_BASE_URL\" >> ./local.properties

    - name: set up Firebase service key
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      run: |
        echo "$GOOGLE_SERVICES" | base64 --decode > app/google-services.json
    
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Check ktlint format
      run: ./gradlew ktlintCheck
      
    - name: Perform Gradle Test
      run: ./gradlew clean test
