name: backend-cd.yml

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        working-directory: ./backend

      - name: Build project
        run: ./gradlew clean build -x test
        working-directory: ./backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mulkkam:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mulkkam:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Stop and remove existing container
        run: |
          if [ "$(docker ps -a -q -f name=backend-app)" ]; then
            docker stop backend-app
            docker rm -f backend-app
          fi

      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mulkkam:latest

      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=root" > ~/mulkkam/.env
          echo "SPRING_PROFILES_ACTIVE=dev" >> ~/mulkkam/.env
          echo "SPRING_DATASOURCE_URL=${{ secrets.DATASOURCE_URL }}" >> ~/mulkkam/.env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}" >> ~/mulkkam/.env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}" >> ~/mulkkam/.env


      - name: Stop existing services
        run: docker compose down
        working-directory: ~/mulkkam

      - name: Start new services
        run: docker compose up -d
        working-directory: ~/mulkkam
