name: backend-cd.yml

on:
  push:
    branches: [ "feat/40" ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to gradlew
        run: chmod +x ./backend/gradlew

      - name: Build project
        run: ./backend/gradlew clean build -x test

      - name: Kill existing app (if running)
        run: |
          PID=$(pgrep -f 'backend.*\.jar')
          if [ -n "$PID" ]; then
            echo "Killing PID $PID"
            kill -9 $PID
          fi

      - name: Run new app in background
        run: |
          JAR_FILE=$(ls ./backend/build/libs/*.jar | grep -v 'plain' | head -n 1)
          nohup java -Dspring.profiles.active=dev -jar "$JAR_FILE" \
            --spring.datasource.url=${{ secrets.DATASOURCE_URL }} \
            --spring.datasource.username=${{ secrets.DATASOURCE_USERNAME }} \
            --spring.datasource.password=${{ secrets.DATASOURCE_PASSWORD }} \
            > app.log 2>&1 &
