name: Auto Assign Reviewers & Assignee

on:
  pull_request:
    types: [opened, labeled, unlabeled, reopened, ready_for_review]

jobs:
  assign-reviewers-and-assignee:
    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewers & assignee
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const androidTeam = ['junseo511', 'devfeijoa', 'hwannow']
            const backendTeam = ['CheChe903', 'Jin409', '2Jin1031', 'minSsan']
      
            const pr = context.payload.pull_request
            const author = pr.user.login
            const labels = pr.labels.map(l => l.name)
      
            const pick = new Set()
            if (labels.includes('AN')) androidTeam.forEach(u => { if (u !== author) pick.add(u) })
            if (labels.includes('BE')) backendTeam.forEach(u => { if (u !== author) pick.add(u) })
      
            const alreadyRequested = pr.requested_reviewers.map(r => r.login)
            const alreadyAssigned = (pr.requested_reviewers || []).map(r => r.login)
            const current = new Set([...alreadyRequested, ...alreadyAssigned])
      
            const eligible = []
            for (const u of pick) {
              if (current.has(u)) continue
              try {
                await github.rest.repos.checkCollaborator({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  username: u
                })
                eligible.push(u)
              } catch {}
            }
      
            if (eligible.length) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                reviewers: eligible
              })
              core.info(`Requested reviewers: ${eligible.join(', ')}`)
            } else {
              core.info('No eligible reviewers to request.')
            }
      
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [author]
            })
            
