name: tag-on-release-merge

on:
  push:
    branches:
      - 'release/v*.*.*'

permissions:
  contents: write

jobs:
  make_tag:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Derive version from branch
        id: ver
        run: |
          BRANCH="${GITHUB_REF_NAME}"          
          VERSION="${BRANCH#release/}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create tag if not exists
        run: |
          VERSION="${{ steps.ver.outputs.version }}"
          if git rev-parse -q --verify "refs/tags/$VERSION" >/dev/null; then
            echo "Tag $VERSION already exists. Skipping."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"
